theme: jekyll-theme-cayman

# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# # About/contact
author:       kkmonlee
  name:       Atul
    url:        http://atulanand.me 

     # Gems
 gems:
  - jekyll-paginate

#Others
markdown: kramdown
